

spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3317/promis?serverTimezone=GMT%2B8
    username: root
    password: root
mybaits: 
  mapper-locations: 
  - classpath*:/mappers/**/*.xml
  type-aliases-package: com.neusoft.promis.security.model












